import type { Request } from '@/generated/models/request-model';
import type { WorkflowDefinition, WorkflowNodeType } from '@/lib/workflow-designer';
import { createIsolatedWorkflowTestService, type InMemoryWorkflowStateProvider, type WorkflowApplicationService } from '@/lib/workflow-application-service';

const actor = { id: 'person-1', displayName: 'Workflow Tester' };
const now = new Date('2026-01-01T09:00:00.000Z');

function assert(condition: boolean, message: string): void { if (!condition) throw new Error(`Workflow test failed: ${message}`); }
function node(id: string, type: WorkflowNodeType, configuration: Record<string, string> = {}) { return { id, type, label: id, position: { x: 0, y: 0 }, configuration }; }
function edge(source: string, target: string, outcome = 'next') { return { id: `${source}-${target}-${outcome}`, source, target, outcome }; }
function definition(nodes: ReturnType<typeof node>[], edges: ReturnType<typeof edge>[]): WorkflowDefinition { return { version: 1, formVersionId: 'form-v1', nodes, edges }; }
function request(): Request { return { id: 'request-1', requestNumber: 'REQ-1', assignedAt: '', assignee: actor, assignmentGroupCode: 'TEAM', cancelledAt: '', catalogItemCode: 'ITEM', closedAt: '', confidentialityLevelId: 'INTERNAL', createdAt: now.toISOString(), createdBy: actor, currentStageId: '', departmentCode: 'IT', description: '', firstRespondedAt: '', formDefinitionId: 'form-1', formVersion: { id: 'form-v1', snapshotLabel: 'v1' }, impactId: 'MEDIUM', priorityKey: 'High', reopenedAt: '', requestedFor: actor, requester: actor, requestSourceKey: 'Portal', requestTypeId: 'REQUEST', resolvedAt: '', serviceCode: 'SERVICE', siteCode: 'HQ', sourceId: 'PORTAL', statusKey: 'New', title: 'Test', updatedAt: now.toISOString(), updatedBy: actor, urgencyId: 'MEDIUM', versionNumber: 1, workspace: { id: 'workspace-1', workspaceName: 'Workspace' } }; }
function start(def: WorkflowDefinition): { service: WorkflowApplicationService; provider: InMemoryWorkflowStateProvider; instanceId: string } { const isolated = createIsolatedWorkflowTestService(request()); const result = isolated.service.start({ request: request(), definition: def, actor, now }); return { ...isolated, instanceId: result.instance.id }; }

export type WorkflowTestEvidence = { name: string; approvals: number; tasks: number; notifications: number; requests: number; relationships: number; finalStatus: string };

export function runWorkflowApplicationServiceTests(): WorkflowTestEvidence[] {
  const evidence: WorkflowTestEvidence[] = [];
  const approvalTask = definition([node('start','Start'), node('approve','Approval',{ assignee: 'requester' }), node('task','FulfilmentTask',{ assignee: 'assignee' }), node('end','End')], [edge('start','approve'), edge('approve','task','approved'), edge('approve','end','rejected'), edge('task','end','completed')]);
  const first = start(approvalTask); let state = first.provider.read(); assert(state.approvals.length === 1, 'approval must be created'); state.approvals[0].statusKey = 'Approved'; first.provider.transact((target) => { target.approvals = state.approvals; }); first.service.resume({ instanceId: first.instanceId, actor, now }); state = first.provider.read(); assert(state.tasks.length === 1, 'task must be created after approval'); state.tasks[0].statusIdKey = 'Completed'; state.tasks[0].completedAt = now.toISOString(); first.provider.transact((target) => { target.tasks = state.tasks; }); const finished = first.service.resume({ instanceId: first.instanceId, actor, now }); assert(finished.instance.status === 'Completed', 'approval/task workflow must complete'); const completedStepCount = first.provider.read().steps.length; first.service.resume({ instanceId: first.instanceId, actor, now }); assert(first.provider.read().steps.length === completedStepCount, 'duplicate resume must not add steps after completion'); evidence.push(summary('Approval then task', first.provider));

  const conditional = definition([node('start','Start'), node('condition','Condition',{ field:'priorityKey', operator:'Equals', value:'High' }), node('true','Notification'), node('false','FieldUpdate',{ targetField:'description', value:'false path' }), node('end','End')], [edge('start','condition'),edge('condition','true','true'),edge('condition','false','false'),edge('true','end'),edge('false','end')]); const conditionRun = start(conditional); assert(conditionRun.provider.read().notifications.length === 1, 'true condition path must execute'); assert(conditionRun.provider.read().instances[0].status === 'Completed', 'condition workflow must complete'); evidence.push(summary('True/false condition', conditionRun.provider));

  const parallel = definition([node('start','Start'),node('parallel','ParallelBranch'),node('a','Notification'),node('b','FieldUpdate',{targetField:'description',value:'branch'}),node('join','Join',{mode:'all'}),node('end','End')],[edge('start','parallel'),edge('parallel','a','branch-a'),edge('parallel','b','branch-b'),edge('a','join'),edge('b','join'),edge('join','end')]); const parallelRun = start(parallel); assert(parallelRun.provider.read().instances[0].status === 'Completed','all-of join must complete'); evidence.push(summary('Parallel all-of join',parallelRun.provider));

  const anyParallel = structuredClone(parallel); const join = anyParallel.nodes.find((item) => item.id === 'join'); if (join) join.configuration.mode = 'any'; const anyRun = start(anyParallel); assert(anyRun.provider.read().instances[0].status === 'Completed','any-of join must complete'); evidence.push(summary('Parallel any-of join',anyRun.provider));

  const wait = definition([node('start','Start'),node('wait','WaitTimer',{minutes:'10'}),node('end','End')],[edge('start','wait'),edge('wait','end','elapsed')]); const waitRun = start(wait); assert(waitRun.provider.read().instances[0].status === 'WaitingForTimer','timer must defer'); assert(waitRun.service.processDue(actor,new Date('2026-01-01T09:05:00.000Z')).length === 0,'early due processing must do nothing'); waitRun.service.processDue(actor,new Date('2026-01-01T09:11:00.000Z')); assert(waitRun.provider.read().instances[0].status === 'Completed','administrator due processing must resume timer'); evidence.push(summary('Wait and due processing',waitRun.provider));

  const retryDef = definition([node('start','Start'),node('bad','FieldUpdate'),node('end','End')],[edge('start','bad'),edge('bad','end')]); const retryRun = start(retryDef); assert(retryRun.provider.read().instances[0].status === 'Failed','invalid node must fail'); retryRun.provider.transact((target) => { const snapshot = target.snapshots[0]; const bad = snapshot.definition.nodes.find((item) => item.id === 'bad'); if (bad) { bad.configuration.targetField = 'description'; bad.configuration.value = 'recovered'; } target.instances[0].idempotencyKeys = target.instances[0].idempotencyKeys.filter((key) => !key.endsWith(':bad')); }); retryRun.service.retry(retryRun.instanceId,actor,now); assert(retryRun.provider.read().instances[0].status === 'Completed','administrator retry must recover'); evidence.push(summary('Failure and retry',retryRun.provider));

  const updateChild = definition([node('start','Start'),node('update','FieldUpdate',{targetField:'description',value:'updated'}),node('child','ChildRequest',{serviceCode:'HR',title:'Child',fieldMappings:''}),node('end','End')],[edge('start','update'),edge('update','child'),edge('child','end')]); const childRun = start(updateChild); const childState = childRun.provider.read(); assert(childState.requests[0].description === 'updated','field update must persist'); assert(childState.requests.length === 2 && childState.relationships.length === 1,'child request and relationship must be created'); evidence.push(summary('Field update and child request',childRun.provider));

  const historical = start(conditional); historical.provider.transact((target) => { const original = target.snapshots[0].definition.nodes.find((item) => item.id === 'true'); if (original) original.label = 'Historical notification'; }); conditional.nodes.find((item) => item.id === 'true')!.label = 'Edited later'; assert(historical.provider.read().snapshots[0].definition.nodes.find((item) => item.id === 'true')?.label === 'Historical notification','instance must use immutable copied snapshot'); evidence.push(summary('Historical version binding',historical.provider));
  return evidence;
}

function summary(name: string, provider: InMemoryWorkflowStateProvider): WorkflowTestEvidence { const state = provider.read(); return { name, approvals: state.approvals.length, tasks: state.tasks.length, notifications: state.notifications.length, requests: state.requests.length, relationships: state.relationships.length, finalStatus: state.instances[0]?.status ?? 'Missing' }; }
