import { useEffect, useMemo, useState, type ChangeEvent } from 'react';
import { AlertCircle, Check, ChevronsUpDown, Info } from 'lucide-react';
import type { FieldDefinition } from '@/generated/models/field-definition-model';
import type { FieldOption } from '@/generated/models/field-option-model';
import type { FieldValidationRule } from '@/generated/models/field-validation-rule-model';
import type { FieldVisibilityRule } from '@/generated/models/field-visibility-rule-model';
import type { FormSection } from '@/generated/models/form-section-model';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { Calendar } from '@/components/ui/calendar';
import { Checkbox } from '@/components/ui/checkbox';
import { Command, CommandEmpty, CommandGroup, CommandInput, CommandItem, CommandList } from '@/components/ui/command';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Textarea } from '@/components/ui/textarea';
import { cn } from '@/lib/utils';
import { applyDynamicRuleEffects, formatDynamicValue, getDynamicFieldState, getDynamicSectionState, InMemoryLookupProvider, parseDynamicValue, type DynamicFileValue, type DynamicFormValue, type DynamicFormValues, type DynamicLookupProvider, type DynamicReferenceValue, type DynamicRuleDefinition } from '@/lib/dynamic-form-runtime';
export { diagnoseDynamicRules, getDynamicFieldState, validateDynamicForm, validateDynamicFormAsync } from '@/lib/dynamic-form-runtime';


export type DynamicFormMode = 'create' | 'draft' | 'preview' | 'approval' | 'read-only' | 'print';
type Props = { sections: FormSection[]; fields: FieldDefinition[]; options: FieldOption[]; visibilityRules: FieldVisibilityRule[] | DynamicRuleDefinition[]; validationRules?: FieldValidationRule[]; values: DynamicFormValues | Record<string, string>; onValuesChange?: (values: DynamicFormValues) => void; onChange?: (fieldId: string, value: string) => void; errors?: Record<string, string>; mode?: DynamicFormMode; className?: string; lookupProviders?: Record<string, DynamicLookupProvider>; authorizedFieldIds?: Set<string> };
const lookupTypes = new Set(['Person', 'Department', 'BusinessUnit', 'Site', 'Asset', 'Lookup', 'CascadingChoice']);
function config(field: FieldDefinition): Record<string, unknown> { try { return field.configuration ? JSON.parse(field.configuration) as Record<string, unknown> : {}; } catch { return {}; } }
function fieldWidth(width: FieldDefinition['widthKey']): string { if (width === 'Half') return 'md:col-span-1'; if (width === 'Third') return 'lg:col-span-1'; if (width === 'TwoThirds') return 'lg:col-span-2'; return 'md:col-span-2 lg:col-span-3'; }
function inputType(field: FieldDefinition): string { if (field.fieldTypeKey === 'Email') return 'email'; if (field.fieldTypeKey === 'Phone') return 'tel'; if (field.fieldTypeKey === 'URL') return 'url'; if (field.fieldTypeKey === 'Number' || field.fieldTypeKey === 'Currency') return 'number'; if (field.fieldTypeKey === 'DateAndTime') return 'datetime-local'; return 'text'; }
function optionReferences(field: FieldDefinition, options: FieldOption[], allowed?: Set<string>): DynamicReferenceValue[] { return options.filter((option: FieldOption) => option.fieldDefinition.id === field.id && option.statusKey === 'Active' && !option.isDeleted && (!allowed || allowed.has(option.value))).sort((first: FieldOption, second: FieldOption) => first.sortOrder - second.sortOrder).map((option: FieldOption) => ({ id: option.value, label: option.label, type: field.fieldTypeKey })); }
export function DynamicFormRenderer({ sections, fields, options, visibilityRules, values, onValuesChange, onChange, errors = {}, mode = 'create', className, lookupProviders = {}, authorizedFieldIds }: Props) {
  const normalized = useMemo(() => { const entries: Array<[string, DynamicFormValue]> = fields.map((field: FieldDefinition): [string, DynamicFormValue] => [field.id, parseDynamicValue(field, values[field.id])]); return Object.fromEntries(entries.filter((entry: [string, DynamicFormValue]) => entry[1] !== null)); }, [fields, values]);
  const [effectiveValues, setEffectiveValues] = useState<DynamicFormValues>(() => applyDynamicRuleEffects(fields, visibilityRules, normalized, authorizedFieldIds));
  const readOnly = mode === 'read-only' || mode === 'approval' || mode === 'print';
  useEffect(() => { setEffectiveValues(applyDynamicRuleEffects(fields, visibilityRules, normalized, authorizedFieldIds)); }, [fields, visibilityRules, normalized, authorizedFieldIds]);
  const update = (fieldId: string, value: DynamicFormValue) => { if (readOnly) return; const next = applyDynamicRuleEffects(fields, visibilityRules, { ...effectiveValues, [fieldId]: value }, authorizedFieldIds); setEffectiveValues(next); onValuesChange?.(next); onChange?.(fieldId, value === null ? '' : typeof value === 'string' ? value : JSON.stringify(value)); };
  return <div className={cn('space-y-5', mode === 'print' && 'print:text-black', className)}>{sections.filter((section: FormSection) => !section.isDeleted).sort((first: FormSection, second: FormSection) => first.sortOrder - second.sortOrder).map((section: FormSection) => { const sectionState = getDynamicSectionState(section, visibilityRules, effectiveValues); if (!sectionState.visible) return null; const sectionFields = fields.filter((field: FieldDefinition) => field.formSection.id === section.id && !field.isDeleted).sort((first: FieldDefinition, second: FieldDefinition) => (first.sortOrder ?? 0) - (second.sortOrder ?? 0)); return <section key={section.id} aria-labelledby={`section-${section.id}`} className="break-inside-avoid rounded-xl border bg-card p-5 text-card-foreground shadow-sm"><header className="mb-4"><h2 id={`section-${section.id}`} className="text-lg font-semibold">{section.title}</h2>{section.instructions && <p className="mt-1 text-sm text-muted-foreground">{section.instructions}</p>}</header>{sectionState.messages.map((message) => <RuleMessage key={message.id} tone={message.tone} text={message.text} />)}<fieldset disabled={sectionState.disabled || readOnly} className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{sectionFields.map((field: FieldDefinition) => { const authorized = !authorizedFieldIds || authorizedFieldIds.has(field.id); const state = getDynamicFieldState(field, visibilityRules, effectiveValues, authorized); if (!state.visible) return null; const fieldOptions = optionReferences(field, options, state.allowedOptionValues); return <div key={field.id} className={fieldWidth(field.widthKey)}><DynamicFieldControl field={field} value={effectiveValues[field.id]} options={fieldOptions} allOptions={options} disabled={state.disabled || state.readOnly || readOnly} required={state.required} error={errors[field.id]} mode={mode} values={effectiveValues} provider={lookupProviders[String(config(field).lookupProviderKey ?? field.fieldTypeKey)]} onChange={(value: DynamicFormValue) => update(field.id, value)} />{state.messages.map((message) => <RuleMessage key={message.id} tone={message.tone} text={message.text} />)}</div>; })}</fieldset></section>; })}</div>;
}
function RuleMessage({ tone, text }: { tone: 'information' | 'warning'; text: string }) { return <Alert className="mb-3"><Info className="size-4" /><AlertDescription>{tone === 'warning' ? `Warning: ${text}` : text}</AlertDescription></Alert>; }
function DynamicFieldControl({ field, value, options, allOptions, disabled, required, error, mode, values, provider, onChange }: { field: FieldDefinition; value?: DynamicFormValue; options: DynamicReferenceValue[]; allOptions: FieldOption[]; disabled: boolean; required: boolean; error?: string; mode: DynamicFormMode; values: DynamicFormValues; provider?: DynamicLookupProvider; onChange: (value: DynamicFormValue) => void }) {
  const id = `dynamic-field-${field.id}`; const label = `${field.label}${required ? ' *' : ''}`; const readOnly = mode === 'read-only' || mode === 'approval' || mode === 'print'; const configuration = config(field);
  if (field.fieldTypeKey === 'Information' || field.fieldTypeKey === 'DisplayOnly') return <div className="rounded-lg bg-muted p-4 text-muted-foreground"><p className="font-medium text-foreground">{field.label}</p>{field.helpText && <p className="mt-1 text-sm">{field.helpText}</p>}</div>;
  if (readOnly) return <div className="space-y-1"><p className="text-sm font-medium">{field.label}</p><div className="min-h-10 rounded-md border bg-background px-3 py-2 text-sm text-foreground">{field.fieldTypeKey === 'RichText' ? <span className="whitespace-pre-wrap">{formatDynamicValue(field, value, allOptions)}</span> : formatDynamicValue(field, value, allOptions)}</div></div>;
  const common = <><Label htmlFor={id}>{label}</Label>{field.helpText && <p id={`${id}-help`} className="text-xs text-muted-foreground">{field.helpText}</p>}</>;
  let control;
  if (field.fieldTypeKey === 'MultiLineText' || field.fieldTypeKey === 'RichText') control = <Textarea id={id} value={typeof value === 'string' ? value : ''} onChange={(event: ChangeEvent<HTMLTextAreaElement>) => onChange(event.target.value)} disabled={disabled} placeholder={field.placeholder} aria-describedby={`${id}-help ${id}-error`} aria-invalid={Boolean(error)} className={field.fieldTypeKey === 'RichText' ? 'min-h-40' : undefined} />;
  else if (field.fieldTypeKey === 'Date') { const selected = typeof value === 'string' && value ? new Date(`${value}T00:00:00`) : undefined; control = <Popover><PopoverTrigger asChild><Button id={id} variant="outline" disabled={disabled} className="w-full justify-start font-normal">{selected && !Number.isNaN(selected.getTime()) ? selected.toLocaleDateString() : field.placeholder || 'Choose a date'}</Button></PopoverTrigger><PopoverContent className="w-auto p-0"><Calendar mode="single" selected={selected} onSelect={(date: Date | undefined) => onChange(date ? `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}` : null)} /></PopoverContent></Popover>; }
  else if (field.fieldTypeKey === 'YesOrNo') control = <div className="flex items-center gap-3 rounded-md border p-3"><Checkbox id={id} checked={value === true} disabled={disabled} onCheckedChange={(checked: boolean | 'indeterminate') => onChange(checked === true)} /><Label htmlFor={id} className="font-normal">{value === true ? 'Yes' : 'No'}</Label></div>;
  else if (field.fieldTypeKey === 'MultipleChoice') { const selected = Array.isArray(value) ? value.filter((item): item is string => typeof item === 'string') : []; control = <fieldset className="space-y-2 rounded-md border p-3" aria-describedby={`${id}-error`}>{options.map((option: DynamicReferenceValue) => <label key={option.id} className="flex items-center gap-2 text-sm"><Checkbox checked={selected.includes(option.id)} disabled={disabled} onCheckedChange={(checked: boolean | 'indeterminate') => onChange(checked === true ? [...selected, option.id] : selected.filter((item: string) => item !== option.id))} />{option.label}</label>)}</fieldset>; }
  else if (field.fieldTypeKey === 'SingleChoice') control = <Select value={typeof value === 'string' && value ? value : 'none'} onValueChange={(next: string) => onChange(next === 'none' ? null : next)} disabled={disabled}><SelectTrigger id={id}><SelectValue placeholder={field.placeholder || 'Choose an option'} /></SelectTrigger><SelectContent><SelectItem value="none">None</SelectItem>{options.filter((option: DynamicReferenceValue) => Boolean(option.id)).map((option: DynamicReferenceValue) => <SelectItem key={option.id} value={option.id}>{option.label}</SelectItem>)}</SelectContent></Select>;
  else if (lookupTypes.has(field.fieldTypeKey)) { let cascadingOptions = options; if (field.fieldTypeKey === 'CascadingChoice') { const parentFieldId = typeof configuration.parentFieldId === 'string' ? configuration.parentFieldId : ''; const parentValue = values[parentFieldId]; const parentId = typeof parentValue === 'string' ? parentValue : parentValue && typeof parentValue === 'object' && 'id' in parentValue ? parentValue.id : ''; cascadingOptions = allOptions.filter((option: FieldOption) => option.fieldDefinition.id === field.id && (!parentId || option.parentOption?.id === parentId || option.parentOption?.label === parentId)).map((option: FieldOption) => ({ id: option.value, label: option.label, type: field.fieldTypeKey })); } control = <LookupControl id={id} field={field} value={value && typeof value === 'object' && !Array.isArray(value) && 'label' in value ? value : undefined} options={cascadingOptions} provider={provider ?? new InMemoryLookupProvider(field.fieldTypeKey, cascadingOptions)} disabled={disabled || (field.fieldTypeKey === 'CascadingChoice' && typeof configuration.parentFieldId === 'string' && !values[configuration.parentFieldId])} values={values} onChange={onChange} />; }
  else if (field.fieldTypeKey === 'Attachment') control = <div className="space-y-2"><Input id={id} type="file" disabled={disabled} multiple={Boolean(configuration.multiple)} accept={typeof configuration.allowedFileTypes === 'string' ? configuration.allowedFileTypes : undefined} onChange={(event: ChangeEvent<HTMLInputElement>) => { const files: DynamicFileValue[] = Array.from(event.target.files ?? []).map((file: File) => ({ id: `${file.name}-${file.lastModified}`, name: file.name, contentType: file.type || 'application/octet-stream', sizeBytes: file.size, status: 'selected' })); onChange(Boolean(configuration.multiple) ? files : files[0] ?? null); }} /><p className="text-xs text-muted-foreground">File metadata is validated locally; file content is not uploaded by this renderer.</p></div>;
  else control = <Input id={id} type={inputType(field)} inputMode={field.fieldTypeKey === 'Currency' || field.fieldTypeKey === 'Number' ? 'decimal' : undefined} value={typeof value === 'number' || typeof value === 'string' ? value : ''} onChange={(event: ChangeEvent<HTMLInputElement>) => onChange(field.fieldTypeKey === 'Number' || field.fieldTypeKey === 'Currency' ? event.target.value === '' ? null : Number(event.target.value) : event.target.value)} disabled={disabled} placeholder={field.placeholder} aria-describedby={`${id}-help ${id}-error`} aria-invalid={Boolean(error)} />;
  return <div className="space-y-2">{common}{control}{error && <p id={`${id}-error`} className="flex items-center gap-1 text-sm text-destructive" role="alert"><AlertCircle className="size-4" />{error}</p>}</div>;
}
function LookupControl({ id, field, value, options, provider, disabled, values, onChange }: { id: string; field: FieldDefinition; value?: DynamicReferenceValue; options: DynamicReferenceValue[]; provider: DynamicLookupProvider; disabled: boolean; values: DynamicFormValues; onChange: (value: DynamicFormValue) => void }) {
  const [open, setOpen] = useState(false); const [search, setSearch] = useState(''); const [records, setRecords] = useState<DynamicReferenceValue[]>(options); const [state, setState] = useState<'idle' | 'loading' | 'error'>('idle');
  useEffect(() => { let active = true; setState('loading'); provider.search({ field, search, values }).then((result: DynamicReferenceValue[]) => { if (active) { setRecords(result); setState('idle'); } }).catch(() => { if (active) setState('error'); }); return () => { active = false; }; }, [field, provider, search, values]);
  return <Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><Button id={id} variant="outline" role="combobox" aria-expanded={open} disabled={disabled} className="w-full justify-between font-normal">{value?.label ?? `Select ${field.label.toLowerCase()}`}<ChevronsUpDown className="size-4" /></Button></PopoverTrigger><PopoverContent className="w-[var(--radix-popover-trigger-width)] p-0"><Command shouldFilter={false}><CommandInput value={search} onValueChange={setSearch} placeholder={`Search ${field.label.toLowerCase()}`} /><CommandList>{state === 'loading' && <div className="p-4 text-sm text-muted-foreground" aria-live="polite">Loading options…</div>}{state === 'error' && <div className="p-4 text-sm text-destructive" role="alert">Options could not be loaded.</div>}{state === 'idle' && records.length === 0 && <CommandEmpty>No options found.</CommandEmpty>}<CommandGroup>{state === 'idle' && records.filter((record: DynamicReferenceValue) => Boolean(record.id)).map((record: DynamicReferenceValue) => <CommandItem key={record.id} value={record.id} onSelect={() => { onChange(record); setOpen(false); }}><Check className={cn('size-4', value?.id === record.id ? 'opacity-100' : 'opacity-0')} /><span><span className="block">{record.label}</span>{record.secondaryLabel && <span className="block text-xs text-muted-foreground">{record.secondaryLabel}</span>}</span></CommandItem>)}</CommandGroup></CommandList></Command></PopoverContent></Popover>;
}
