import { useEffect, useMemo, useRef, useState, type ChangeEvent, type FormEvent } from 'react';
import { Link, Navigate, useParams } from 'react-router-dom';
import { Archive, ArrowLeft, Blocks, CheckCircle2, ChevronDown, ChevronUp, ClipboardCheck, Copy, FilePlus2, GripVertical, History, LayoutTemplate, Plus, Redo2, Save, Search, Send, Sparkles, Trash2, Undo2 } from 'lucide-react';
import { toast } from 'sonner';
import { useWorkspaceContext } from '@/contexts/workspace-context';
import { useCreateService, useServiceList, useUpdateService } from '@/generated/hooks/use-service';
import { useCreateFormDefinition, useFormDefinitionList, useUpdateFormDefinition } from '@/generated/hooks/use-form-definition';
import { useFormVersionList, useCreateFormVersion, useUpdateFormVersion } from '@/generated/hooks/use-form-version';
import { useServiceCategoryList } from '@/generated/hooks/use-service-category';
import { useFormSectionList, useCreateFormSection, useUpdateFormSection } from '@/generated/hooks/use-form-section';
import { useFieldDefinitionList, useCreateFieldDefinition, useUpdateFieldDefinition } from '@/generated/hooks/use-field-definition';
import { useFieldOptionList, useCreateFieldOption } from '@/generated/hooks/use-field-option';
import { useFieldValidationRuleList, useCreateFieldValidationRule } from '@/generated/hooks/use-field-validation-rule';
import { useFieldVisibilityRuleList, useCreateFieldVisibilityRule } from '@/generated/hooks/use-field-visibility-rule';
import { useCreateConfigurationAuditEvent } from '@/generated/hooks/use-configuration-audit-event';
import { useServiceGovernanceProfileList } from '@/generated/hooks/use-service-governance-profile';
import { useCreatePublicationApproval, usePublicationApprovalList } from '@/generated/hooks/use-publication-approval';
import { useAutomationActionList } from '@/generated/hooks/use-automation-action';
import { useAutomationConditionList } from '@/generated/hooks/use-automation-condition';
import { useAutomationRuleList } from '@/generated/hooks/use-automation-rule';
import { useAutomationTriggerList } from '@/generated/hooks/use-automation-trigger';
import { useLifecycleDefinitionList } from '@/generated/hooks/use-lifecycle-definition';
import { useStatusDefinitionList } from '@/generated/hooks/use-status-definition';
import { useStatusTransitionList } from '@/generated/hooks/use-status-transition';
import { useServiceTargetPolicyList } from '@/generated/hooks/use-service-target-policy';
import { useServiceTargetRuleList } from '@/generated/hooks/use-service-target-rule';
import { useServicePermissionList } from '@/generated/hooks/use-service-permission';
import { useCatalogItemList } from '@/generated/hooks/use-catalog-item';
import { useCatalogItemAudienceList } from '@/generated/hooks/use-catalog-item-audience';
import { useCatalogItemFormAssignmentList } from '@/generated/hooks/use-catalog-item-form-assignment';
import type { Service } from '@/generated/models/service-model';
import { ServiceReadinessAssessment } from '@/components/service-readiness-assessment';
import { assessServiceReadiness } from '@/lib/service-readiness-assessment';
import { parseWorkflowDefinition, validateWorkflowDefinition } from '@/lib/workflow-designer';
import { validateLifecycle } from '@/lib/lifecycle-engine';
import type { FormDefinition } from '@/generated/models/form-definition-model';
import type { FormVersion } from '@/generated/models/form-version-model';
import type { FormSection } from '@/generated/models/form-section-model';
import { FieldDefinitionFieldTypeKeyToLabel, type FieldDefinition, type FieldDefinitionFieldTypeKey } from '@/generated/models/field-definition-model';
import type { FieldOption } from '@/generated/models/field-option-model';
import type { FieldValidationRule, FieldValidationRuleRuleTypeKey } from '@/generated/models/field-validation-rule-model';
import type { FieldVisibilityRule, FieldVisibilityRuleEffectKey, FieldVisibilityRuleOperatorKey } from '@/generated/models/field-visibility-rule-model';
import { DynamicFormRenderer, diagnoseDynamicRules } from '@/components/dynamic-form-renderer';
import { compareServiceVersions } from '@/lib/service-version-impact';
import { buildDependencyMap } from '@/lib/dependency-mapping';
import { serviceTemplateLibrary, type ServiceTemplateDefinition } from '@/lib/service-template-library';
import { createComponentFieldCode, reusableFormComponents, type ReusableFormComponentDefinition } from '@/lib/reusable-form-components';
import { DependencyMap } from '@/components/dependency-map';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';

const supportedTypes: FieldDefinitionFieldTypeKey[] = ['Text', 'MultiLineText', 'RichText', 'Number', 'Currency', 'Date', 'DateAndTime', 'Email', 'Phone', 'URL', 'YesOrNo', 'SingleChoice', 'MultipleChoice', 'Person', 'Department', 'BusinessUnit', 'Lookup', 'CascadingChoice', 'Attachment', 'Information'];
type FieldDraft = { label: string; fieldCode: string; fieldTypeKey: FieldDefinitionFieldTypeKey; placeholder: string; helpText: string; defaultValue: string; required: boolean; requesterVisible: boolean; readOnly1: boolean; searchable: boolean; reportable: boolean; sensitive: boolean; widthKey: 'Full' | 'Half' | 'Third' | 'TwoThirds'; options: string; customError: string; lookupSource: string; allowedFileTypes: string; maximumFileSize: string };

const emptyField: FieldDraft = { label: '', fieldCode: '', fieldTypeKey: 'Text', placeholder: '', helpText: '', defaultValue: '', required: false, requesterVisible: true, readOnly1: false, searchable: true, reportable: true, sensitive: false, widthKey: 'Full', options: '', customError: '', lookupSource: '', allowedFileTypes: '', maximumFileSize: '' };
type UndoAction = { fieldId: string; before: Partial<FieldDefinition>; after: Partial<FieldDefinition> };

export default function ServiceBuilderPage() {
  const { workspaceCode = '' } = useParams();
  const { activeWorkspace, currentPerson, can } = useWorkspaceContext();
  const { data: categories = [] } = useServiceCategoryList();
  const { data: services = [] } = useServiceList();
  const { data: forms = [] } = useFormDefinitionList();
  const { data: versions = [] } = useFormVersionList();
  const { data: sections = [] } = useFormSectionList();
  const { data: fields = [] } = useFieldDefinitionList();
  const { data: options = [] } = useFieldOptionList();
  const { data: governanceProfiles = [] } = useServiceGovernanceProfileList();
  const { data: publicationApprovals = [] } = usePublicationApprovalList();
  const { data: validationRules = [] } = useFieldValidationRuleList();
  const { data: visibilityRules = [] } = useFieldVisibilityRuleList();
  const { data: automationRules = [] } = useAutomationRuleList();
  const { data: automationTriggers = [] } = useAutomationTriggerList();
  const { data: automationConditions = [] } = useAutomationConditionList();
  const { data: automationActions = [] } = useAutomationActionList();
  const { data: lifecycleDefinitions = [] } = useLifecycleDefinitionList();
  const { data: lifecycleStatuses = [] } = useStatusDefinitionList();
  const { data: lifecycleTransitions = [] } = useStatusTransitionList();
  const { data: targetPolicies = [] } = useServiceTargetPolicyList();
  const { data: targetRules = [] } = useServiceTargetRuleList();
  const { data: servicePermissions = [] } = useServicePermissionList();
  const { data: catalogItems = [] } = useCatalogItemList();
  const { data: catalogAudiences = [] } = useCatalogItemAudienceList();
  const { data: catalogAssignments = [] } = useCatalogItemFormAssignmentList();
  const createService = useCreateService(); const updateService = useUpdateService(); const createForm = useCreateFormDefinition(); const updateForm = useUpdateFormDefinition(); const createVersion = useCreateFormVersion(); const updateVersion = useUpdateFormVersion();
  const createSection = useCreateFormSection(); const updateSection = useUpdateFormSection(); const createField = useCreateFieldDefinition(); const updateField = useUpdateFieldDefinition();
  const createOption = useCreateFieldOption(); const createValidation = useCreateFieldValidationRule(); const createVisibility = useCreateFieldVisibilityRule(); const createAudit = useCreateConfigurationAuditEvent(); const createPublicationApproval = useCreatePublicationApproval();
  const [serviceId, setServiceId] = useState(''); const [formId, setFormId] = useState(''); const [librarySearch, setLibrarySearch] = useState(''); const [activeTab, setActiveTab] = useState('form'); const [changeReason, setChangeReason] = useState('');
  const [templateSearch, setTemplateSearch] = useState(''); const [selectedTemplate, setSelectedTemplate] = useState<ServiceTemplateDefinition>(); const [templateName, setTemplateName] = useState(''); const [templateBusy, setTemplateBusy] = useState(false);

  const [selectedFieldId, setSelectedFieldId] = useState(''); const [fieldDraft, setFieldDraft] = useState<FieldDraft | null>(null); const [fieldSectionId, setFieldSectionId] = useState('');
  const [undoStack, setUndoStack] = useState<UndoAction[]>([]); const [redoStack, setRedoStack] = useState<UndoAction[]>([]); const [lastSavedAt, setLastSavedAt] = useState<string>();
  const [ruleSourceId, setRuleSourceId] = useState(''); const [ruleEffect, setRuleEffect] = useState<FieldVisibilityRuleEffectKey>('Show'); const [ruleOperator, setRuleOperator] = useState<FieldVisibilityRuleOperatorKey>('Equals'); const [ruleValue, setRuleValue] = useState('');
  const [validationType, setValidationType] = useState<FieldValidationRuleRuleTypeKey>('MinimumLength'); const [validationValue, setValidationValue] = useState(''); const [validationError, setValidationError] = useState('');
  const dragId = useRef<string | undefined>(undefined);
  const workspaceServices = useMemo(() => services.filter((item: Service) => item.workspace.id === activeWorkspace?.id && !item.isDeleted), [activeWorkspace?.id, services]);
  const workspaceForms = useMemo(() => forms.filter((item: FormDefinition) => item.workspace.id === activeWorkspace?.id), [activeWorkspace?.id, forms]);
  const selectedService = workspaceServices.find((item: Service) => item.id === serviceId) ?? workspaceServices[0];
  const selectedForm = workspaceForms.find((item: FormDefinition) => item.id === formId) ?? workspaceForms.find((item: FormDefinition) => item.name1.toLowerCase().includes(selectedService?.serviceCode.toLowerCase() ?? '')) ?? workspaceForms[0];
  const formVersions = versions.filter((item: FormVersion) => item.formDefinition.id === selectedForm?.id && !item.isDeleted).sort((a: FormVersion, b: FormVersion) => b.versionNumber - a.versionNumber);
  const draftVersion = formVersions.find((item: FormVersion) => item.statusKey === 'Draft'); const publishedVersion = formVersions.find((item: FormVersion) => item.statusKey === 'Published'); const activeVersion = draftVersion ?? publishedVersion ?? formVersions[0];
  const activeSections = sections.filter((item: FormSection) => item.formVersionID.id === activeVersion?.id && !item.isDeleted).sort((a: FormSection, b: FormSection) => a.sortOrder - b.sortOrder);
  const activeFields = fields.filter((item: FieldDefinition) => item.formVersionID.id === activeVersion?.id && !item.isDeleted).sort((a: FieldDefinition, b: FieldDefinition) => (a.sortOrder ?? 0) - (b.sortOrder ?? 0));
  const governanceProfile = governanceProfiles.find((profile) => profile.service.id === selectedService?.id && profile.statusKey === 'Active');
  const pendingPublication = publicationApprovals.find((approval) => approval.formVersion.id === draftVersion?.id && approval.statusKey === 'Pending' && !approval.isDeleted);
  const publishedFields = fields.filter((item: FieldDefinition) => item.formVersionID.id === publishedVersion?.id && !item.isDeleted); const selectedField = activeFields.find((item: FieldDefinition) => item.id === selectedFieldId);
  const activeValidation = validationRules.filter((rule: FieldValidationRule) => activeFields.some((field: FieldDefinition) => field.id === rule.fieldDefinition.id) && !rule.isDeleted);
  const activeVisibility = visibilityRules.filter((rule: FieldVisibilityRule) => activeFields.some((field: FieldDefinition) => field.id === rule.fieldDefinition.id) && !rule.isDeleted);
  const impacts = compareServiceVersions(activeFields, publishedFields); const diagnostics = diagnoseDynamicRules(activeFields, activeVisibility);
  const dependencyMap = useMemo(() => buildDependencyMap({
    fields: activeFields,
    validationRules: activeValidation,
    visibilityRules: activeVisibility,
    fieldImpacts: impacts,
    workflow: selectedService ? { id: selectedService.id, label: `${selectedService.serviceName} workflow`, configuration: activeVersion?.configurationSnapshot } : undefined,
    lifecycle: selectedService ? { id: selectedService.id, label: `${selectedService.serviceName} lifecycle`, configuration: selectedService.instructions } : undefined,
    sla: selectedService ? { id: selectedService.id, label: `${selectedService.serviceName} SLA`, configuration: selectedService.availabilityConfiguration } : undefined,
    reports: selectedService ? [{ id: selectedService.id, label: `${selectedService.serviceName} reporting`, configuration: selectedService.reportingConfiguration }] : [],
    templates: serviceTemplateLibrary.map((template: ServiceTemplateDefinition) => ({ id: template.key, label: template.name, configuration: JSON.stringify(template) })),
  }), [activeFields, activeValidation, activeVisibility, activeVersion?.configurationSnapshot, impacts, selectedService]);
  const readiness = useMemo(() => {
    const serviceRule = automationRules.find((rule) => rule.workspace.id === activeWorkspace?.id && rule.serviceCode === selectedService?.serviceCode);
    const trigger = automationTriggers.find((item) => item.automationRule.id === serviceRule?.id && item.active);
    const workflow = serviceRule ? parseWorkflowDefinition(trigger, automationActions.filter((item) => item.automationRule.id === serviceRule.id), automationConditions.filter((item) => item.automationRule.id === serviceRule.id)) : undefined;
    const workflowErrors = workflow ? validateWorkflowDefinition(workflow, new Set(activeFields.map((field: FieldDefinition) => field.fieldCode))).filter((finding) => finding.severity === 'error').map((finding) => finding.message) : [];
    const lifecycle = lifecycleDefinitions.find((item) => item.workspace.id === activeWorkspace?.id && item.statusKey === 'Active' && (item.serviceCode === selectedService?.serviceCode || item.catalogItemCode === selectedService?.serviceCode || item.default1));
    const lifecycleReport = lifecycle ? validateLifecycle(lifecycle, lifecycleStatuses, lifecycleTransitions) : undefined;
    const item = catalogItems.find((catalogItem) => catalogItem.workspace.id === activeWorkspace?.id && catalogItem.service.id === selectedService?.id && catalogItem.statusKey !== 'Retired');
    const slaRules = targetRules.filter((rule) => rule.workspace.id === activeWorkspace?.id && rule.active && (rule.serviceCode === selectedService?.serviceCode || rule.catalogItemCode === item?.itemCode));
    const slaConfigured = slaRules.some((rule) => targetPolicies.some((policy) => policy.id === rule.serviceTargetPolicy.id && policy.active));
    return assessServiceReadiness({
      sectionCount: activeSections.length, fieldCount: activeFields.length, requiredFieldCount: activeFields.filter((field: FieldDefinition) => field.required).length, validationRuleCount: activeValidation.length,
      ruleDiagnosticMessages: diagnostics.map((diagnostic) => diagnostic.message), activeRuleCount: activeVisibility.length, workflowConfigured: Boolean(serviceRule && workflow), workflowBoundToVersion: Boolean(workflow?.formVersionId && (workflow.formVersionId === activeVersion?.id || workflow.formVersionId === publishedVersion?.id)), workflowErrorMessages: workflowErrors,
      lifecycleConfigured: Boolean(lifecycle), lifecycleIssueMessages: lifecycleReport?.issues.map((issue) => issue.message) ?? [], slaConfigured, permissionsConfigured: Boolean(governanceProfile || servicePermissions.some((permission) => permission.workspaceId.id === activeWorkspace?.id && permission.serviceCode === selectedService?.serviceCode && permission.statusKey === 'Active')),
      audienceConfigured: Boolean(item && catalogAudiences.some((audience) => audience.catalogItem.id === item.id && audience.statusKey === 'Active' && audience.isEligible) && catalogAssignments.some((assignment) => assignment.catalogItem.id === item.id && assignment.statusKey === 'Active')),
      reportableFieldCount: activeFields.filter((field: FieldDefinition) => field.reportable && !field.sensitive).length, reportingConfigured: Boolean(selectedService?.reportingConfiguration), breakingDependencyMessages: dependencyMap.impacts.filter((impact) => impact.severity === 'breaking').map((impact) => impact.detail), dependencyWarningMessages: dependencyMap.impacts.filter((impact) => impact.severity === 'warning').map((impact) => impact.detail),
    });
  }, [activeFields, activeSections.length, activeValidation.length, activeVersion?.id, activeVisibility.length, activeWorkspace?.id, automationActions, automationConditions, automationRules, automationTriggers, catalogAssignments, catalogAudiences, catalogItems, dependencyMap.impacts, diagnostics, governanceProfile, lifecycleDefinitions, lifecycleStatuses, lifecycleTransitions, publishedVersion?.id, selectedService, servicePermissions, targetPolicies, targetRules]);
  const busy = createVersion.isPending || updateVersion.isPending || createSection.isPending || updateSection.isPending || createField.isPending || updateField.isPending;
  const componentInstance = (component: ReusableFormComponentDefinition) => activeFields.filter((field: FieldDefinition) => field.fieldCode.startsWith(component.key.replaceAll('-', '_'))).length + 1;
  useEffect(() => { if (!fieldDraft || !selectedField) return; const timer = window.setTimeout(() => { void saveFieldDraft(selectedField, fieldDraft, false); }, 900); return () => window.clearTimeout(timer); }, [fieldDraft]);

  if (!activeWorkspace) return <Navigate to="/no-workspace-access" replace />;
  if (!can('workspace.administer')) return <Navigate to={`/w/${workspaceCode}`} replace />;
  const workspace = activeWorkspace;

  const ensureDraft = async () => {
    if (!selectedForm || !currentPerson) return undefined; if (draftVersion) return draftVersion; const source = publishedVersion ?? formVersions[0]; const nextNumber = Math.max(0, ...formVersions.map((item: FormVersion) => item.versionNumber)) + 1;
    const created = await createVersion.mutateAsync({ snapshotLabel: `${selectedForm.name1} v${nextNumber}`, configurationSnapshot: source?.configurationSnapshot, formDefinition: { id: selectedForm.id, name1: selectedForm.name1 }, statusKey: 'Draft', versionNumber: nextNumber, workspace: { id: workspace.id, workspaceName: workspace.workspaceName }, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), isDeleted: false });
    if (source) { const sourceSections = sections.filter((item: FormSection) => item.formVersionID.id === source.id && !item.isDeleted); for (const sourceSection of sourceSections) { const { id: _sectionId, ...sectionData } = sourceSection; void _sectionId; const clonedSection = await createSection.mutateAsync({ ...sectionData, formVersionID: { id: created.id, snapshotLabel: created.snapshotLabel }, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); const sourceFields = fields.filter((item: FieldDefinition) => item.formVersionID.id === source.id && item.formSection.id === sourceSection.id && !item.isDeleted); for (const sourceField of sourceFields) { const { id: _fieldId, ...fieldData } = sourceField; void _fieldId; await createField.mutateAsync({ ...fieldData, formSection: { id: clonedSection.id, title: clonedSection.title }, formVersionID: { id: created.id, snapshotLabel: created.snapshotLabel }, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); } } }
    toast.success(`Draft version ${nextNumber} created from the latest configuration.`); return created;
  };
  const addReusableComponent = async (component: ReusableFormComponentDefinition) => {
    const version = await ensureDraft();
    if (!version || !selectedForm) return;
    const now = new Date().toISOString();
    const instance = componentInstance(component);
    const section = await createSection.mutateAsync({ title: component.name, description: component.description, instructions: 'Reusable component', formDefinition: { id: selectedForm.id, name1: selectedForm.name1 }, formVersionID: { id: version.id, snapshotLabel: version.snapshotLabel }, sortOrder: activeSections.length + 1, workspace: { id: workspace.id, workspaceName: workspace.workspaceName }, createdAt: now, updatedAt: now, isDeleted: false });
    for (const [index, template] of component.fields.entries()) {
      const fieldCode = createComponentFieldCode(component.key, instance, template.key);
      const field = await createField.mutateAsync({ label: template.label, fieldCode, fieldTypeKey: template.type, placeholder: template.placeholder, helpText: template.helpText, required: template.required ?? false, requesterVisible: true, readOnly1: false, searchable: true, reportable: true, sensitive: false, widthKey: template.width ?? 'Full', configuration: JSON.stringify({ reusableComponent: component.key, componentInstance: instance, componentFieldKey: template.key, ...template.configuration }), agentOnly: false, sortOrder: index + 1, formDefinition: { id: selectedForm.id, name1: selectedForm.name1 }, formSection: { id: section.id, title: section.title }, formVersionID: { id: version.id, snapshotLabel: version.snapshotLabel }, workspace: { id: workspace.id, workspaceName: workspace.workspaceName }, createdAt: now, updatedAt: now, isDeleted: false });
      await Promise.all((template.options ?? []).map((label: string, optionIndex: number) => createOption.mutateAsync({ label, value: label.toLowerCase().replace(/[^a-z0-9]+/g, '-'), fieldDefinition: { id: field.id, label: field.label }, sortOrder: optionIndex + 1, statusKey: 'Active', workspace: { id: workspace.id, workspaceName: workspace.workspaceName }, createdAt: now, updatedAt: now, isDeleted: false })));
    }
    toast.success(`${component.name} added as editable metadata.`);
  };

  const openTemplate = (template: ServiceTemplateDefinition) => { setSelectedTemplate(template); setTemplateName(template.name); };
  const createFromTemplate = async (publishAfterCreation: boolean) => {
    if (!selectedTemplate || !currentPerson) return;
    const category = categories.find((item) => item.workspace.id === workspace.id && !item.isDeleted);
    if (!category) return toast.error('Create an active service category before using templates.');
    setTemplateBusy(true);
    try {
      const now = new Date().toISOString();
      const suffix = Date.now().toString().slice(-6);
      const serviceCode = `${selectedTemplate.key.replaceAll('-', '_').toUpperCase()}_${suffix}`;
      const form = await createForm.mutateAsync({ name1: `${templateName.trim() || selectedTemplate.name} form`, description: selectedTemplate.description, currentVersionNumber: 1, statusKey: 'Draft', workspace: { id: workspace.id, workspaceName: workspace.workspaceName } });
      const version = await createVersion.mutateAsync({ snapshotLabel: `${templateName.trim() || selectedTemplate.name} v1`, configurationSnapshot: JSON.stringify({ templateKey: selectedTemplate.key, templateKinds: selectedTemplate.kinds, workflow: selectedTemplate.workflow, lifecycle: selectedTemplate.lifecycle, sla: selectedTemplate.sla, reporting: selectedTemplate.reporting }), formDefinition: { id: form.id, name1: form.name1 }, statusKey: 'Draft', versionNumber: 1, workspace: { id: workspace.id, workspaceName: workspace.workspaceName }, createdAt: now, updatedAt: now, isDeleted: false });
      for (const [sectionIndex, sectionTemplate] of selectedTemplate.sections.entries()) {
        const section = await createSection.mutateAsync({ title: sectionTemplate.title, description: sectionTemplate.description, instructions: '', formDefinition: { id: form.id, name1: form.name1 }, formVersionID: { id: version.id, snapshotLabel: version.snapshotLabel }, sortOrder: sectionIndex + 1, workspace: { id: workspace.id, workspaceName: workspace.workspaceName }, createdAt: now, updatedAt: now, isDeleted: false });
        for (const [fieldIndex, template] of sectionTemplate.fields.entries()) {
          const field = await createField.mutateAsync({ label: template.label, fieldCode: template.key, fieldTypeKey: template.type, placeholder: template.placeholder, helpText: template.helpText, required: template.required ?? false, requesterVisible: true, readOnly1: false, searchable: true, reportable: Boolean(template.configuration?.reportable ?? true), sensitive: template.configuration?.sensitivity === 'restricted', widthKey: template.width ?? 'Full', configuration: JSON.stringify({ templateKey: selectedTemplate.key, ...template.configuration }), agentOnly: false, sortOrder: fieldIndex + 1, formDefinition: { id: form.id, name1: form.name1 }, formSection: { id: section.id, title: section.title }, formVersionID: { id: version.id, snapshotLabel: version.snapshotLabel }, workspace: { id: workspace.id, workspaceName: workspace.workspaceName }, createdAt: now, updatedAt: now, isDeleted: false });
          await Promise.all((template.options ?? []).map((label: string, optionIndex: number) => createOption.mutateAsync({ label, value: label.toLowerCase().replace(/[^a-z0-9]+/g, '-'), fieldDefinition: { id: field.id, label: field.label }, sortOrder: optionIndex + 1, statusKey: 'Active', workspace: { id: workspace.id, workspaceName: workspace.workspaceName }, createdAt: now, updatedAt: now, isDeleted: false })));
        }
      }
      const service = await createService.mutateAsync({ serviceName: templateName.trim() || selectedTemplate.name, serviceCode, description: selectedTemplate.description, instructions: `Created from ${selectedTemplate.name}. Customize and validate before publishing.`, defaultAssignmentGroupCode: 'UNASSIGNED', requesterEligible: true, serviceCategory: { id: category.id, name1: category.name1 }, workspace: { id: workspace.id, workspaceName: workspace.workspaceName }, lifecycleStateKey: publishAfterCreation ? 'Published' : 'Draft', statusKey: publishAfterCreation ? 'Active' : 'Inactive', currentPublishedFormVersion: publishAfterCreation ? { id: version.id, snapshotLabel: version.snapshotLabel } : undefined, reportingConfiguration: JSON.stringify({ templateKey: selectedTemplate.key, fields: selectedTemplate.reporting }), audienceConfiguration: JSON.stringify({ scope: 'workspace' }), availabilityConfiguration: JSON.stringify({ enabled: publishAfterCreation }), sortOrder: workspaceServices.length + 1, createdAt: now, updatedAt: now, isDeleted: false, owner: { id: currentPerson.id, displayName: currentPerson.displayName } });
      if (publishAfterCreation) { await updateVersion.mutateAsync({ id: version.id, changedFields: { statusKey: 'Published', publishedAt: now, publishedBy: { id: currentPerson.id, displayName: currentPerson.displayName }, updatedAt: now } }); await updateForm.mutateAsync({ id: form.id, changedFields: { statusKey: 'Published' } }); }
      await createAudit.mutateAsync({ configurationAuditEventName: `${publishAfterCreation ? 'Published' : 'Created'} ${service.serviceName} from template`, actionKey: 'Created', actor: { id: currentPerson.id, displayName: currentPerson.displayName }, newValue: JSON.stringify({ templateKey: selectedTemplate.key, serviceId: service.id, formVersionId: version.id }), occurredAt: now, scopeKey: 'Service', settingKey: 'serviceTemplate', sourceKey: 'ServiceOverride', targetRecordID: service.id, workspace: { id: workspace.id, workspaceName: workspace.workspaceName } });
      setServiceId(service.id); setFormId(form.id); setSelectedTemplate(undefined); toast.success(`${service.serviceName} ${publishAfterCreation ? 'published' : 'created as an independent draft'}.`);
    } catch (error: unknown) { toast.error(error instanceof Error ? error.message : 'Template creation failed.'); } finally { setTemplateBusy(false); }
  };


  const addSection = async () => { const version = await ensureDraft(); if (!version || !selectedForm) return; await createSection.mutateAsync({ title: `Section ${activeSections.length + 1}`, description: 'Requester information', instructions: '', formDefinition: { id: selectedForm.id, name1: selectedForm.name1 }, formVersionID: { id: version.id, snapshotLabel: version.snapshotLabel }, sortOrder: activeSections.length + 1, workspace: { id: workspace.id, workspaceName: workspace.workspaceName }, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), isDeleted: false }); toast.success('Section added.'); };
  const openField = (section: FormSection, field?: FieldDefinition, type?: FieldDefinitionFieldTypeKey) => { setFieldSectionId(section.id); setSelectedFieldId(field?.id ?? ''); const configuration = field?.configuration ? JSON.parse(field.configuration) as Record<string, string> : {}; setFieldDraft(field ? { label: field.label, fieldCode: field.fieldCode, fieldTypeKey: field.fieldTypeKey, placeholder: field.placeholder ?? '', helpText: field.helpText ?? '', defaultValue: field.defaultValue ?? '', required: field.required, requesterVisible: field.requesterVisible, readOnly1: field.readOnly1, searchable: field.searchable ?? false, reportable: field.reportable ?? false, sensitive: field.sensitive, widthKey: field.widthKey ?? 'Full', options: options.filter((option: FieldOption) => option.fieldDefinition.id === field.id && !option.isDeleted).map((option: FieldOption) => option.label).join('\n'), customError: configuration.customError ?? '', lookupSource: configuration.lookupSource ?? '', allowedFileTypes: configuration.allowedFileTypes ?? '', maximumFileSize: configuration.maximumFileSize ?? '' } : { ...emptyField, fieldTypeKey: type ?? 'Text' }); };
  const saveFieldDraft = async (field: FieldDefinition, draft: FieldDraft, notify = true) => { const configuration = JSON.stringify({ customError: draft.customError, lookupSource: draft.lookupSource, allowedFileTypes: draft.allowedFileTypes, maximumFileSize: draft.maximumFileSize }); const changed = { label: draft.label.trim(), placeholder: draft.placeholder || undefined, helpText: draft.helpText || undefined, defaultValue: draft.defaultValue || undefined, required: draft.required, requesterVisible: draft.requesterVisible, readOnly1: draft.readOnly1, searchable: draft.searchable, reportable: draft.reportable, sensitive: draft.sensitive, widthKey: draft.widthKey, configuration, updatedAt: new Date().toISOString() }; await updateField.mutateAsync({ id: field.id, changedFields: changed }); setLastSavedAt(new Date().toISOString()); if (notify) toast.success('Field saved.'); };
  const saveField = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!fieldDraft || !selectedForm) return; const section = activeSections.find((item: FormSection) => item.id === fieldSectionId); const version = await ensureDraft(); if (!section || !version || !fieldDraft.label.trim() || !fieldDraft.fieldCode.trim()) return toast.error('Label and stable key are required.'); if (activeFields.some((item: FieldDefinition) => item.fieldCode.toLowerCase() === fieldDraft.fieldCode.toLowerCase() && item.id !== selectedField?.id)) return toast.error('Stable key must be unique.'); if (selectedField) { await saveFieldDraft(selectedField, fieldDraft); return; } const configuration = JSON.stringify({ customError: fieldDraft.customError, lookupSource: fieldDraft.lookupSource, allowedFileTypes: fieldDraft.allowedFileTypes, maximumFileSize: fieldDraft.maximumFileSize }); const saved = await createField.mutateAsync({ label: fieldDraft.label.trim(), fieldCode: fieldDraft.fieldCode.trim(), fieldTypeKey: fieldDraft.fieldTypeKey, placeholder: fieldDraft.placeholder || undefined, helpText: fieldDraft.helpText || undefined, defaultValue: fieldDraft.defaultValue || undefined, required: fieldDraft.required, requesterVisible: fieldDraft.requesterVisible, readOnly1: fieldDraft.readOnly1, searchable: fieldDraft.searchable, reportable: fieldDraft.reportable, sensitive: fieldDraft.sensitive, widthKey: fieldDraft.widthKey, configuration, agentOnly: false, sortOrder: activeFields.filter((item: FieldDefinition) => item.formSection.id === section.id).length + 1, formDefinition: { id: selectedForm.id, name1: selectedForm.name1 }, formSection: { id: section.id, title: section.title }, formVersionID: { id: version.id, snapshotLabel: version.snapshotLabel }, workspace: { id: workspace.id, workspaceName: workspace.workspaceName }, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), isDeleted: false }); const labels = fieldDraft.options.split('\n').map((value: string) => value.trim()).filter(Boolean); await Promise.all(labels.map((label: string, index: number) => createOption.mutateAsync({ label, value: label.toLowerCase().replace(/[^a-z0-9]+/g, '-'), fieldDefinition: { id: saved.id, label }, sortOrder: index + 1, statusKey: 'Active', workspace: { id: workspace.id, workspaceName: workspace.workspaceName }, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), isDeleted: false }))); setSelectedFieldId(saved.id); toast.success('Field added.'); };
  const updateOrder = async (field: FieldDefinition, direction: -1 | 1) => { const peers = activeFields.filter((item: FieldDefinition) => item.formSection.id === field.formSection.id); const index = peers.findIndex((item: FieldDefinition) => item.id === field.id); const other = peers[index + direction]; if (!other || !draftVersion) return; const before = { sortOrder: field.sortOrder }; const after = { sortOrder: other.sortOrder }; await Promise.all([updateField.mutateAsync({ id: field.id, changedFields: after }), updateField.mutateAsync({ id: other.id, changedFields: before })]); setUndoStack((items: UndoAction[]) => [...items, { fieldId: field.id, before, after }]); setRedoStack([]); };
  const undo = async () => { const action = undoStack.at(-1); if (!action) return; await updateField.mutateAsync({ id: action.fieldId, changedFields: action.before }); setUndoStack((items: UndoAction[]) => items.slice(0, -1)); setRedoStack((items: UndoAction[]) => [...items, action]); }; const redo = async () => { const action = redoStack.at(-1); if (!action) return; await updateField.mutateAsync({ id: action.fieldId, changedFields: action.after }); setRedoStack((items: UndoAction[]) => items.slice(0, -1)); setUndoStack((items: UndoAction[]) => [...items, action]); };
  const duplicateField = async (field: FieldDefinition) => { const { id: _id, ...data } = field; void _id; await createField.mutateAsync({ ...data, label: `${field.label} copy`, fieldCode: `${field.fieldCode}_copy_${Date.now().toString().slice(-4)}`, sortOrder: activeFields.filter((item: FieldDefinition) => item.formSection.id === field.formSection.id).length + 1, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }); toast.success('Field cloned with a new stable key.'); };
  const addValidation = async () => { if (!selectedField || !validationValue || !validationError) return toast.error('Comparison value and error message are required.'); await createValidation.mutateAsync({ errorMessage: validationError, comparisonValue: validationValue, fieldDefinition: { id: selectedField.id, label: selectedField.label }, ruleTypeKey: validationType, sortOrder: activeValidation.length + 1, statusKey: 'Active', workspace: { id: workspace.id, workspaceName: workspace.workspaceName }, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), isDeleted: false }); toast.success('Validation added.'); };
  const addRule = async () => { if (!selectedField || !ruleSourceId) return toast.error('Select a source field.'); const source = activeFields.find((item: FieldDefinition) => item.id === ruleSourceId); if (!source) return; await createVisibility.mutateAsync({ ruleName: `${ruleEffect} ${selectedField.label}`, comparisonValue: ruleValue || undefined, dependentFieldDefinition: { id: source.id, label: source.label }, effectKey: ruleEffect, fieldDefinition: { id: selectedField.id, label: selectedField.label }, operatorKey: ruleOperator, sortOrder: activeVisibility.length + 1, statusKey: 'Active', workspace: { id: workspace.id, workspaceName: workspace.workspaceName }, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString(), isDeleted: false }); toast.success('Conditional rule added.'); };
  const archive = async () => { if (!draftVersion) return; await updateVersion.mutateAsync({ id: draftVersion.id, changedFields: { statusKey: 'Retired', updatedAt: new Date().toISOString() } }); toast.success('Draft archived without changing published requests.'); };
  const cloneService = async () => { if (!selectedService) return; await updateService.mutateAsync({ id: selectedService.id, changedFields: { updatedAt: new Date().toISOString() } }); await ensureDraft(); toast.success('A clone-ready draft version was created; service identity remains unchanged for safety.'); };
  const publish = async () => {
    if (!selectedForm || !draftVersion || !selectedService || !currentPerson) return;
    if (readiness.status === 'Not Ready') { setActiveTab('readiness'); return toast.error('Resolve all Not Ready findings before publishing.'); }
    const breakingImpact = dependencyMap.impacts.find((item) => item.severity === 'breaking' && item.affectedNodeIds.length > 0);
    if (breakingImpact) { setActiveTab('dependencies'); return toast.error(`Resolve dependency impact before publishing: ${breakingImpact.title}`); }
    if (!changeReason.trim()) return toast.error('Enter a change reason before requesting publication.');
    const now = new Date().toISOString();
    const snapshot = JSON.stringify({ formId: selectedForm.id, version: draftVersion.versionNumber, sections: activeSections, fields: activeFields, validationRules: activeValidation, visibilityRules: activeVisibility, dependencyMap, changeReason: changeReason.trim() });
    if (governanceProfile?.makerCheckerRequired) {
      if (pendingPublication) return toast.info('This version is already waiting for publication approval.');
      const reviewDate = new Date(); reviewDate.setDate(reviewDate.getDate() + 7);
      await updateVersion.mutateAsync({ id: draftVersion.id, changedFields: { configurationSnapshot: snapshot, updatedAt: now } });
      await createPublicationApproval.mutateAsync({ approvalName: `${selectedForm.name1} v${draftVersion.versionNumber}`, changeReason: changeReason.trim(), formVersion: { id: draftVersion.id, snapshotLabel: draftVersion.snapshotLabel }, isDeleted: false, makerCheckerSatisfied: false, requestedAt: now, requestedBy: { id: currentPerson.id, displayName: currentPerson.displayName }, reviewDate: reviewDate.toISOString(), service: { id: selectedService.id, serviceName: selectedService.serviceName }, statusKey: 'Pending', workspace: { id: workspace.id, workspaceName: workspace.workspaceName } });
      await createAudit.mutateAsync({ configurationAuditEventName: `Requested publication ${selectedForm.name1} v${draftVersion.versionNumber}`, actionKey: 'Created', actor: { id: currentPerson.id, displayName: currentPerson.displayName }, newValue: JSON.stringify({ changeReason: changeReason.trim(), publisherId: governanceProfile.publisher.id }), occurredAt: now, scopeKey: 'Service', settingKey: 'publicationApproval', sourceKey: 'ServiceOverride', targetRecordID: selectedService.id, workspace: { id: workspace.id, workspaceName: workspace.workspaceName } });
      setChangeReason(''); toast.success(`Publication sent to ${governanceProfile.publisher.displayName} for independent approval.`); return;
    }
    await updateVersion.mutateAsync({ id: draftVersion.id, changedFields: { statusKey: 'Published', publishedAt: now, publishedBy: { id: currentPerson.id, displayName: currentPerson.displayName }, configurationSnapshot: snapshot, updatedAt: now } });
    await updateForm.mutateAsync({ id: selectedForm.id, changedFields: { statusKey: 'Published', currentVersionNumber: draftVersion.versionNumber } });
    await updateService.mutateAsync({ id: selectedService.id, changedFields: { lifecycleStateKey: 'Published', statusKey: 'Active', currentPublishedFormVersion: { id: draftVersion.id, snapshotLabel: draftVersion.snapshotLabel }, updatedAt: now } });
    await createAudit.mutateAsync({ configurationAuditEventName: `Published ${selectedForm.name1} v${draftVersion.versionNumber}`, actionKey: 'Updated', actor: { id: currentPerson.id, displayName: currentPerson.displayName }, newValue: snapshot, occurredAt: now, scopeKey: 'Service', settingKey: 'publishedFormVersion', sourceKey: 'ServiceOverride', targetRecordID: selectedService.id, workspace: { id: workspace.id, workspaceName: workspace.workspaceName } });
    setChangeReason(''); toast.success('Immutable service version published.');
  };
  const tabSummary: Record<string, string> = { audience: selectedService?.audienceConfiguration || 'Audience uses catalog eligibility and workspace membership.', lifecycle: 'Lifecycle is connected through the existing lifecycle definition for this service.', workflow: 'Workflow uses existing automation, approvals, and task metadata.', sla: 'SLA uses existing service target policies and business calendars.', permissions: 'Permissions use workspace roles and service grants.', reporting: `${activeFields.filter((item: FieldDefinition) => item.reportable).length} reportable fields selected.`, versions: `${formVersions.length} retained versions.` };
  return <main className="flex-1 p-4 md:p-6"><div className="mx-auto max-w-[1600px] space-y-5">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><Button variant="ghost" size="sm" asChild><Link to={`/w/${workspaceCode}/settings/catalog`}><ArrowLeft className="size-4" />Catalog administration</Link></Button><h1 className="mt-2 text-2xl font-semibold">Service builder</h1><p className="text-sm text-muted-foreground">Design, validate, and publish governed services without code.</p></div><div className="flex flex-wrap gap-2"><Button asChild><Link to={`/w/${workspaceCode}/settings/service-builder/guided`}><Sparkles className="size-4" />Guided creation</Link></Button><Button variant="outline" asChild><Link to={`/w/${workspaceCode}/settings/service-builder/ai-design`}><Sparkles className="size-4" />AI design</Link></Button><Button variant="outline" asChild><Link to={`/w/${workspaceCode}/settings/service-governance`}>Governance</Link></Button><Button variant="outline" onClick={() => setActiveTab('readiness')}><ClipboardCheck className="size-4" />{readiness.status}</Button><Button variant="outline" onClick={() => setActiveTab('templates')}><LayoutTemplate className="size-4" />Template library</Button><Button variant="outline" onClick={() => void undo()} disabled={!undoStack.length}><Undo2 className="size-4" />Undo</Button><Button variant="outline" onClick={() => void redo()} disabled={!redoStack.length}><Redo2 className="size-4" />Redo</Button><Button variant="outline" onClick={() => void cloneService()}><Copy className="size-4" />Clone version</Button><Button variant="outline" onClick={() => void archive()} disabled={!draftVersion}><Archive className="size-4" />Archive</Button><Button onClick={() => void publish()} disabled={!draftVersion || busy || Boolean(pendingPublication)}><Send className="size-4" />{governanceProfile?.makerCheckerRequired ? 'Request publication' : 'Publish'}</Button></div></header>
    <Card><CardContent className="grid gap-4 p-4 md:grid-cols-[1fr_1fr_auto]"><div className="space-y-2"><Label>Service</Label><Select value={selectedService?.id ?? 'none'} onValueChange={setServiceId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{workspaceServices.filter((item: Service) => Boolean(item.id)).map((item: Service) => <SelectItem key={item.id} value={item.id}>{item.serviceName}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Form</Label><Select value={selectedForm?.id ?? 'none'} onValueChange={setFormId}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{workspaceForms.filter((item: FormDefinition) => Boolean(item.id)).map((item: FormDefinition) => <SelectItem key={item.id} value={item.id}>{item.name1}</SelectItem>)}</SelectContent></Select></div><div className="flex items-end gap-2"><Badge variant={pendingPublication ? 'default' : draftVersion ? 'secondary' : 'outline'}>{pendingPublication ? 'Approval pending' : draftVersion ? `Draft v${draftVersion.versionNumber}` : activeVersion ? `${activeVersion.statusKey} v${activeVersion.versionNumber}` : 'No version'}</Badge>{lastSavedAt && <span className="text-xs text-muted-foreground">Autosaved {new Date(lastSavedAt).toLocaleTimeString()}</span>}</div><div className="space-y-2 md:col-span-2"><Label>Change reason</Label><Textarea value={changeReason} onChange={(event: ChangeEvent<HTMLTextAreaElement>) => setChangeReason(event.target.value)} placeholder="Explain why this version should be published" /></div><div className="flex items-end"><p className="text-xs text-muted-foreground">{governanceProfile ? `Owner: ${governanceProfile.serviceOwner.displayName} · Publisher: ${governanceProfile.publisher.displayName} · Review ${new Date(governanceProfile.nextReviewDate).toLocaleDateString()}` : 'No governance profile: direct publication remains available for backward compatibility.'}</p></div></CardContent></Card>
    <Tabs value={activeTab} onValueChange={setActiveTab}><TabsList className="h-auto flex-wrap">{['templates', 'form', 'rules', 'audience', 'lifecycle', 'workflow', 'sla', 'permissions', 'reporting', 'dependencies', 'readiness', 'versions'].map((tab: string) => <TabsTrigger key={tab} value={tab}>{tab[0].toUpperCase() + tab.slice(1)}</TabsTrigger>)}</TabsList>
      <TabsContent value="templates"><div className="space-y-4"><Card><CardHeader><CardTitle>Service template library</CardTitle><CardDescription>Launch an independent service draft with form, workflow, lifecycle, SLA, and reporting starter configuration.</CardDescription></CardHeader><CardContent><div className="relative max-w-md"><Search className="absolute left-3 top-3 size-4 text-muted-foreground" /><Input value={templateSearch} onChange={(event: ChangeEvent<HTMLInputElement>) => setTemplateSearch(event.target.value)} className="pl-9" placeholder="Search starter templates" /></div></CardContent></Card><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{serviceTemplateLibrary.filter((template: ServiceTemplateDefinition) => `${template.name} ${template.description} ${template.category}`.toLowerCase().includes(templateSearch.toLowerCase())).map((template: ServiceTemplateDefinition) => <Card key={template.key} className="flex flex-col"><CardHeader><div className="flex items-start justify-between gap-3"><div><CardTitle>{template.name}</CardTitle><CardDescription className="mt-1">{template.description}</CardDescription></div><Badge variant="secondary">{template.category}</Badge></div></CardHeader><CardContent className="flex flex-1 flex-col justify-between gap-4"><div className="flex flex-wrap gap-1">{template.kinds.map((kind: string) => <Badge key={kind} variant="outline">{kind}</Badge>)}</div><Button onClick={() => openTemplate(template)}><LayoutTemplate className="size-4" />Preview and use</Button></CardContent></Card>)}</div></div></TabsContent>
      <TabsContent value="form"><div className="grid gap-4 xl:grid-cols-[260px_minmax(0,1fr)_360px]">
        <aside className="space-y-4"><Card><CardHeader><CardTitle className="text-base">Field library</CardTitle><CardDescription>Search fields and reusable components.</CardDescription></CardHeader><CardContent className="space-y-2"><div className="relative"><Search className="absolute left-3 top-3 size-4 text-muted-foreground" /><Input value={librarySearch} onChange={(event: ChangeEvent<HTMLInputElement>) => setLibrarySearch(event.target.value)} className="pl-9" placeholder="Search library" /></div>{supportedTypes.filter((type: FieldDefinitionFieldTypeKey) => FieldDefinitionFieldTypeKeyToLabel[type].toLowerCase().includes(librarySearch.toLowerCase())).map((type: FieldDefinitionFieldTypeKey) => <Button key={type} variant="outline" className="w-full justify-start" disabled={!draftVersion || !activeSections.length} onClick={() => openField(activeSections[0], undefined, type)}><Plus className="size-4" />{FieldDefinitionFieldTypeKeyToLabel[type]}</Button>)}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Blocks className="size-4" />Reusable components</CardTitle><CardDescription>Each component expands into standard sections, fields, options, and typed configuration.</CardDescription></CardHeader><CardContent className="space-y-2">{reusableFormComponents.filter((component: ReusableFormComponentDefinition) => `${component.name} ${component.description} ${component.category}`.toLowerCase().includes(librarySearch.toLowerCase())).map((component: ReusableFormComponentDefinition) => <Button key={component.key} variant="outline" className="h-auto w-full justify-start whitespace-normal py-3 text-left" disabled={!draftVersion} onClick={() => void addReusableComponent(component)}><span><span className="block font-medium">{component.name}</span><span className="block text-xs text-muted-foreground">{component.description}</span></span></Button>)}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Sections</CardTitle></CardHeader><CardContent className="space-y-2">{activeSections.map((section: FormSection) => <div key={section.id} className="flex items-center justify-between rounded-md border p-2"><span className="text-sm font-medium">{section.title}</span><Button size="icon-sm" variant="ghost" onClick={() => openField(section)}><Plus className="size-4" /></Button></div>)}<Button variant="outline" className="w-full" onClick={() => void addSection()}><Plus className="size-4" />Add section</Button></CardContent></Card></aside>
        <section className="space-y-4"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Live requester canvas</h2><p className="text-sm text-muted-foreground">The shared renderer shows the published experience.</p></div><Button variant="outline" onClick={() => void ensureDraft()}><FilePlus2 className="size-4" />New draft</Button></div>{activeSections.map((section: FormSection) => <Card key={section.id}><CardHeader><CardTitle className="text-base">{section.title}</CardTitle></CardHeader><CardContent className="space-y-2">{activeFields.filter((field: FieldDefinition) => field.formSection.id === section.id).map((field: FieldDefinition, index: number, peers: FieldDefinition[]) => <div key={field.id} draggable={Boolean(draftVersion)} onDragStart={() => { dragId.current = field.id; }} onDragOver={(event: React.DragEvent<HTMLDivElement>) => event.preventDefault()} onDrop={() => { const dragged = activeFields.find((item: FieldDefinition) => item.id === dragId.current); if (dragged && dragged.formSection.id === field.formSection.id) void updateOrder(dragged, dragged.sortOrder! < field.sortOrder! ? 1 : -1); }} className={`flex items-center gap-2 rounded-md border p-2 ${selectedFieldId === field.id ? 'bg-accent text-accent-foreground' : 'bg-background text-foreground'}`}><GripVertical className="size-4" /><button type="button" className="min-w-0 flex-1 text-left" onClick={() => openField(section, field)}><span className="font-medium">{field.label}</span><span className="block text-xs">{field.fieldCode} · {FieldDefinitionFieldTypeKeyToLabel[field.fieldTypeKey]}</span></button><Button size="icon-sm" variant="ghost" aria-label="Move up" disabled={!draftVersion || index === 0} onClick={() => void updateOrder(field, -1)}><ChevronUp className="size-4" /></Button><Button size="icon-sm" variant="ghost" aria-label="Move down" disabled={!draftVersion || index === peers.length - 1} onClick={() => void updateOrder(field, 1)}><ChevronDown className="size-4" /></Button><Button size="icon-sm" variant="ghost" aria-label="Clone field" onClick={() => void duplicateField(field)}><Copy className="size-4" /></Button><Button size="icon-sm" variant="ghost" aria-label="Remove field" onClick={() => void updateField.mutateAsync({ id: field.id, changedFields: { isDeleted: true } })}><Trash2 className="size-4" /></Button></div>)}<DynamicFormRenderer sections={[section]} fields={activeFields.filter((field: FieldDefinition) => field.formSection.id === section.id)} options={options} validationRules={activeValidation} visibilityRules={activeVisibility} values={{}} mode="preview" /></CardContent></Card>)}</section>
        <aside><Card className="sticky top-5"><CardHeader><CardTitle className="text-base">{selectedField ? selectedField.label : 'Field properties'}</CardTitle><CardDescription>Properties autosave after a short pause.</CardDescription></CardHeader><CardContent>{fieldDraft ? <form className="space-y-4" onSubmit={(event: FormEvent<HTMLFormElement>) => void saveField(event)}><div className="space-y-2"><Label>Label</Label><Input value={fieldDraft.label} onChange={(event: ChangeEvent<HTMLInputElement>) => setFieldDraft({ ...fieldDraft, label: event.target.value })} /></div><div className="space-y-2"><Label>Stable key</Label><Input value={fieldDraft.fieldCode} disabled={Boolean(selectedField)} onChange={(event: ChangeEvent<HTMLInputElement>) => setFieldDraft({ ...fieldDraft, fieldCode: event.target.value })} /></div><div className="space-y-2"><Label>Help text</Label><Textarea value={fieldDraft.helpText} onChange={(event: ChangeEvent<HTMLTextAreaElement>) => setFieldDraft({ ...fieldDraft, helpText: event.target.value })} /></div><div className="space-y-2"><Label>Default value</Label><Input value={fieldDraft.defaultValue} onChange={(event: ChangeEvent<HTMLInputElement>) => setFieldDraft({ ...fieldDraft, defaultValue: event.target.value })} /></div><div className="space-y-2"><Label>Custom error</Label><Input value={fieldDraft.customError} onChange={(event: ChangeEvent<HTMLInputElement>) => setFieldDraft({ ...fieldDraft, customError: event.target.value })} /></div><div className="space-y-2"><Label>Lookup source</Label><Input value={fieldDraft.lookupSource} onChange={(event: ChangeEvent<HTMLInputElement>) => setFieldDraft({ ...fieldDraft, lookupSource: event.target.value })} placeholder="Provider and collection" /></div>{fieldDraft.fieldTypeKey === 'Attachment' && <div className="grid gap-3"><Input value={fieldDraft.allowedFileTypes} onChange={(event: ChangeEvent<HTMLInputElement>) => setFieldDraft({ ...fieldDraft, allowedFileTypes: event.target.value })} placeholder="Allowed types" /><Input value={fieldDraft.maximumFileSize} onChange={(event: ChangeEvent<HTMLInputElement>) => setFieldDraft({ ...fieldDraft, maximumFileSize: event.target.value })} placeholder="Maximum MB" /></div>}<div className="grid gap-2">{([{ key: 'required', label: 'Required' }, { key: 'searchable', label: 'Searchable' }, { key: 'reportable', label: 'Reportable' }, { key: 'sensitive', label: 'Sensitive' }] as const).map((item) => <div key={item.key} className="flex items-center justify-between rounded-md border p-2"><Label>{item.label}</Label><Switch checked={fieldDraft[item.key]} onCheckedChange={(checked: boolean) => setFieldDraft({ ...fieldDraft, [item.key]: checked })} /></div>)}</div><Button type="submit" className="w-full"><Save className="size-4" />{selectedField ? 'Save now' : 'Add field'}</Button></form> : <p className="text-sm text-muted-foreground">Select a field or add one from the library.</p>}</CardContent></Card></aside>
      </div></TabsContent>
      <TabsContent value="rules"><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>Conditional rules</CardTitle><CardDescription>Configure behavior for the selected field.</CardDescription></CardHeader><CardContent className="space-y-3"><Select value={ruleSourceId || 'none'} onValueChange={(value: string) => setRuleSourceId(value === 'none' ? '' : value)}><SelectTrigger><SelectValue placeholder="Source field" /></SelectTrigger><SelectContent><SelectItem value="none">Select source</SelectItem>{activeFields.filter((item: FieldDefinition) => item.id && item.id !== selectedFieldId).map((item: FieldDefinition) => <SelectItem key={item.id} value={item.id}>{item.label}</SelectItem>)}</SelectContent></Select><div className="grid grid-cols-2 gap-2"><Select value={ruleOperator} onValueChange={(value: FieldVisibilityRuleOperatorKey) => setRuleOperator(value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{['Equals','NotEquals','Contains','IsEmpty','IsNotEmpty'].map((value: string) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select><Select value={ruleEffect} onValueChange={(value: FieldVisibilityRuleEffectKey) => setRuleEffect(value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{['Show','Hide','Require','ReadOnly'].map((value: string) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div><Input value={ruleValue} onChange={(event: ChangeEvent<HTMLInputElement>) => setRuleValue(event.target.value)} placeholder="Comparison value" /><Button onClick={() => void addRule()} disabled={!selectedField}>Add rule</Button></CardContent></Card><Card><CardHeader><CardTitle>Validation</CardTitle></CardHeader><CardContent className="space-y-3"><Select value={validationType} onValueChange={(value: FieldValidationRuleRuleTypeKey) => setValidationType(value)}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{['MinimumLength','MaximumLength','MinimumValue','MaximumValue','Pattern','Email','Phone','URL'].map((value: string) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select><Input value={validationValue} onChange={(event: ChangeEvent<HTMLInputElement>) => setValidationValue(event.target.value)} placeholder="Comparison value" /><Input value={validationError} onChange={(event: ChangeEvent<HTMLInputElement>) => setValidationError(event.target.value)} placeholder="Custom error message" /><Button onClick={() => void addValidation()} disabled={!selectedField}>Add validation</Button>{diagnostics.map((item) => <div key={item.message} className="rounded-md bg-destructive p-3 text-sm text-destructive-foreground">{item.message}</div>)}</CardContent></Card></div></TabsContent>
      {['audience','lifecycle','workflow','sla','permissions','reporting'].map((tab: string) => <TabsContent key={tab} value={tab}><Card><CardHeader><CardTitle>{tab[0].toUpperCase() + tab.slice(1)}</CardTitle><CardDescription>Connected configuration</CardDescription></CardHeader><CardContent><p className="text-sm text-muted-foreground">{tabSummary[tab]}</p><Button variant="outline" className="mt-4" asChild><Link to={tab === 'lifecycle' ? `/w/${workspaceCode}/settings/lifecycles` : tab === 'workflow' ? `/w/${workspaceCode}/settings/automation` : tab === 'reporting' ? `/w/${workspaceCode}/reports/builder` : `/w/${workspaceCode}/settings/catalog`}>Open detailed configuration</Link></Button></CardContent></Card></TabsContent>)}
      <TabsContent value="versions"><div className="grid gap-4 lg:grid-cols-[1fr_1.2fr]"><Card><CardHeader><CardTitle>Version history</CardTitle></CardHeader><CardContent className="space-y-2">{formVersions.map((version: FormVersion) => <div key={version.id} className="flex items-center justify-between rounded-md border p-3"><div><p className="font-medium">{version.snapshotLabel}</p><p className="text-xs text-muted-foreground">{version.publishedAt ? new Date(version.publishedAt).toLocaleString() : 'Unpublished draft'}</p></div><Badge variant={version.statusKey === 'Published' ? 'default' : 'outline'}>{version.statusKey}</Badge></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Publication impact</CardTitle><CardDescription>Review changes before publishing.</CardDescription></CardHeader><CardContent className="space-y-2">{impacts.length ? impacts.map((impact) => <div key={`${impact.kind}-${impact.key}`} className="rounded-md border p-3"><div className="flex justify-between gap-3"><p className="font-medium">{impact.label}</p><Badge variant="secondary">{impact.kind}</Badge></div><p className="mt-1 text-xs text-muted-foreground">Impacts: {impact.impacts.join(', ')}</p></div>) : <div className="flex items-center gap-2 rounded-md bg-secondary p-3 text-secondary-foreground"><CheckCircle2 className="size-4" />No field changes from the latest published version.</div>}</CardContent></Card></div></TabsContent>
    </Tabs>
    <Dialog open={Boolean(selectedTemplate)} onOpenChange={(open: boolean) => { if (!open) setSelectedTemplate(undefined); }}>
      <DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-3xl">
        <DialogHeader><DialogTitle>{selectedTemplate?.name}</DialogTitle><DialogDescription>{selectedTemplate?.description}</DialogDescription></DialogHeader>
        {selectedTemplate && <div className="space-y-5"><div className="space-y-2"><Label>Independent service name</Label><Input value={templateName} onChange={(event: ChangeEvent<HTMLInputElement>) => setTemplateName(event.target.value)} /></div><div className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle className="text-base">Form preview</CardTitle></CardHeader><CardContent className="space-y-3">{selectedTemplate.sections.map((section) => <div key={section.title} className="rounded-md border p-3"><p className="font-medium">{section.title}</p><p className="text-xs text-muted-foreground">{section.description}</p><div className="mt-2 flex flex-wrap gap-1">{section.fields.map((field) => <Badge key={field.key} variant="outline">{field.label}</Badge>)}</div></div>)}</CardContent></Card><Card><CardHeader><CardTitle className="text-base">Connected configuration</CardTitle></CardHeader><CardContent className="space-y-3"><div><p className="font-medium">Workflow</p><p className="text-sm text-muted-foreground">{selectedTemplate.workflow.join(' → ')}</p></div><div><p className="font-medium">Lifecycle</p><p className="text-sm text-muted-foreground">{selectedTemplate.lifecycle.join(' → ')}</p></div><div><p className="font-medium">SLA</p><p className="text-sm text-muted-foreground">Respond in {selectedTemplate.sla.responseHours}h · resolve in {selectedTemplate.sla.resolutionHours}h</p></div><div><p className="font-medium">Reporting</p><p className="text-sm text-muted-foreground">{selectedTemplate.reporting.join(', ')}</p></div></CardContent></Card></div></div>}
        <DialogFooter><Button variant="outline" onClick={() => setSelectedTemplate(undefined)}>Cancel</Button><Button variant="secondary" onClick={() => void createFromTemplate(false)} disabled={templateBusy || !templateName.trim()}><Copy className="size-4" />Clone as draft</Button><Button onClick={() => void createFromTemplate(true)} disabled={templateBusy || !templateName.trim()}><Send className="size-4" />Create and publish</Button></DialogFooter>
      </DialogContent>
    </Dialog>
  </div></main>;
}
